config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  devise_for :users
  resources :articles

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :articles
  accepts_nested_attributes_for :articles, allow_destroy: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @user = current_user
    if @article.save
      flash[:notice] = "Post added successfully"
      redirect_to article_path(@article)
    else
      flash[:error] = @article.errors.full_messages.join(". ")
      render :new
    end
  end

  def show
    @article = Article.find(params[:id])
    @user = @article.user
  end

  private

  def article_params
    params.require(:article).permit(:title, :body).merge(user: current_user)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/new.html.erb
<h1 align="center">Submit a New Post</h1>
<div class="form">
  <%= form_for([@user, @article], url: articles_path, method: :post) do |f| %>
    <div align="center" class="field">
      <%= f.label :title %>:<br />
      <%= f.text_field :title, autofocus: true, size: "30x1", placeholder: "'Bat Boy Sighted in NYC'" %>
    </div><br />

    <div align="center" class="field">
      <%= f.label :body %>:<br />
      <%= f.text_area :body, autofocus: true, size: "40x10", placeholder: "Insert your body parts here."; %>
    </div><br />

    <div align="center" class="actions">
      <%= f.submit "Submit" %>
    </div>
  <% end %>
</div>

app/views/articles/show.html.erb
<div style="width: 60%; margin: auto; padding: 10px; background-color: yellow">
  <div class="article-title">
  <h1 style="padding: 10px; background-color: orange"><%= @article.title %></h1>
  </div>
  <h3>by <%= @user.first_name %> <%= @user.last_name %></h3>
  <div class="article-body">
    <p style="padding: 10px; background-color: pink"><%= @article.body %></p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Message Board</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if !current_user %>
          <li><%= link_to 'Sign up', new_user_registration_path %></li>
          <li><%= link_to 'Sign in', new_user_session_path %></li>
        <% else %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Your Account<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
              <li><a href="#">See Post History</a></li>
              <li><%= link_to "Cancel my account", registration_path(resource_name), data: { confirm: "Are you sure?" }, method: :delete %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<%= yield %>

</body>
</html>

app/views/pages/home.html.erb
<div class="jumbotron" style="padding: 30px; margin: 30px;">
  <h1>Welcome to the message board of the internet!</h1>
  <p>Dreamers, doers, thinkers, eaters, all are welcome here at the Message Board. Find out how to contribute and send messages on the internet! I'm sure it's a hospitable place.</p>
  <p><a class="btn btn-primary btn-lg" href="/users/sign_up" role="button">Become a denizen</a></p>
</div>

app/views/posts/show.html.erb
<div class="article-title">
<h1>@article.title</h1>
</div>
<div class="article-body">
  <h4>@article.body</h4>
</div>